working on view model
AlinaRodina99/projects pull request #30
Opened 2020-04-26 10:43 UTC by AlinaRodina99

2020-10-24 10:32 UTC, yurii-litvinov requested changes
- А зачем в репозитории .exe-шник? :)
- У меня прошло только два теста из семи. В CI тесты, похоже, вообще не запускались (dotnet test не нашёл ни одного, похоже, или просто не знает, что делать с проектом под .NET Framework)
- Абсолютные размеры кнопок заставляют форму очень страшно выглядеть при ресайзе
- Форму можно сжать до совсем нерабочего состояния
- А зачем на фрме поля ввода имени файла и папки, если есть верхнее меню, где можно выбрать файл и папку для загрузки?
- Если нажать на Download, оно говорит, что нет такого файла, если нажать на Download all, оно начинает качать Рихтера (одного), немного думает и падает на клиенте :)

2020-10-24 10:32 UTC, yurii-litvinov commented on homework.sem3/task5/GUI_task5/GUIforFTP/GUIforFTP/ViewModel.cs
> +                OnPropertyChanged("FileForDownloading");
CallerMemberName у OnPropertyChanged указан, можно "FileForDownloading" явно не передавать (и даже не стоит так делать, потому что если мы в процессе рефакторинга переименуем свойство, нотификации будут слаться неправильно

2020-10-24 10:32 UTC, yurii-litvinov commented on homework.sem3/task5/GUI_task5/GUIforFTP/GUIforFTP/ViewModel.cs
> +            public bool Type { get; set; }
Для большей читабельности стоило бы сделать enum из двух элементов. Иначе я вот вижу `if (listElement != null && listElement.Type)` и думаю "что?"

2020-10-24 10:32 UTC, yurii-litvinov commented on homework.sem3/task5/GUI_task5/GUIforFTP/GUIforFTP/ViewModel.cs
> +            return;
Зачем return в конце функции? :)

2020-10-24 10:32 UTC, yurii-litvinov commented on homework.sem3/task5/GUI_task5/GUIforFTP/GUIforFTP/ViewModel.cs
> +        /// <returns></returns>
Пустые тэги не нужны

2020-10-24 10:32 UTC, yurii-litvinov commented on homework.sem3/task5/GUI_task5/GUIforFTP/GUIforFTP/ViewModel.cs
> +            public string ImagePath { get; set; }
По-хорошему, надо ещё комментариев

2020-10-24 10:32 UTC, yurii-litvinov commented on homework.sem3/task5/GUI_task5/GUIforFTP/ServerApp/Server.cs
> +    public class Server
И тут

2020-10-24 17:22 UTC, AlinaRodina99 commented
> * А зачем в репозитории .exe-шник? :)
> * У меня прошло только два теста из семи. В CI тесты, похоже, вообще не запускались (dotnet test не нашёл ни одного, похоже, или просто не знает, что делать с проектом под .NET Framework)
> * Абсолютные размеры кнопок заставляют форму очень страшно выглядеть при ресайзе
> * Форму можно сжать до совсем нерабочего состояния
> * А зачем на фрме поля ввода имени файла и папки, если есть верхнее меню, где можно выбрать файл и папку для загрузки?
> * Если нажать на Download, оно говорит, что нет такого файла, если нажать на Download all, оно начинает качать Рихтера (одного), немного думает и падает на клиенте :)

Вот поле для ввода папки я делала для того, чтобы была еще возможность выбрать не только существующую в текущей папке, но и еще создать новую для скачивания, а вот с полем для файла лишнее. Просто вот с папкой не знаю как по-другому сделать(

2020-10-24 18:07 UTC, yurii-litvinov commented
А, так это папка на целевой машине? :) Не, тогда вполне ок. Можно, правда, воспользоваться стандартным окном выбора папки, что-нить как здесь: https://stackoverflow.com/questions/1922204/open-directory-dialog

2020-10-26 10:58 UTC, yurii-litvinov requested changes
Теперь всё даже почти работает (почти, потому что попытка указать "." в качестве рабочей папки крешит приложение при попытке что-то скачать). Осталось поправить небольшие замечания и что-то сделать с крешем.

2020-10-26 10:58 UTC, yurii-litvinov commented on homework.sem3/task5/GUI_task5/GUIforFTP/GUIforFTP/ViewModel.cs
> +            public string ElementName { get; set; }
И ещё комментариев? :)

2020-10-26 10:58 UTC, yurii-litvinov commented on homework.sem3/task5/GUI_task5/GUIforFTP/ServerApp/Server.cs
> +                throw new ArgumentOutOfRangeException("Port should be from 0 to 65535");
И тут не поправили

2020-10-26 10:58 UTC, yurii-litvinov commented on homework.sem3/task5/GUI_task5/GUIforFTP/GUIforFTP/Client.cs
> +                        fileResult.Close();
Что-то с using-ами вообще исправления не сложились. Если есть причины делать как у Вас --- откомментите и поясните, я не требую обязательно исправить. Но просто забить на замечания нельзя :)

2020-10-26 11:36 UTC, AlinaRodina99 commented on homework.sem3/task5/GUI_task5/GUIforFTP/ServerApp/Server.cs
> +                throw new ArgumentOutOfRangeException("Port should be from 0 to 65535");
Ой ,с юзингами в клиенте почему-то не закоммитилось, поправлю

2020-10-26 11:41 UTC, AlinaRodina99 commented on homework.sem3/task5/GUI_task5/GUIforFTP/ServerApp/Server.cs
> +                throw new ArgumentOutOfRangeException("Port should be from 0 to 65535");
И с портами тоже исправляла, но странно, не закоммитилось

2020-10-26 13:48 UTC, yurii-litvinov requested changes
Запретить все точки в пути для скачивания --- очень плохая идея, хотя бы потому, что путь до проекта содержит точку (homework.sem3). Ну и все относительные пути (с ..) таким образом будут зарезаны. Если слеши правда тоже нельзя, это незачёт сразу :) Поправьте, пожалуйста.

2020-10-26 13:48 UTC, yurii-litvinov commented on homework.sem3/task5/GUI_task5/GUIforFTP/GUIforFTP/Client.cs
> +                    tcpClient?.Close();
А он и так сделает Close, он же теперь using. Хуже, конечно, не будет, но зачем

2020-10-26 13:54 UTC, AlinaRodina99 commented
> Запретить все точки в пути для скачивания --- очень плохая идея, хотя бы потому, что путь до проекта содержит точку (homework.sem3). Ну и все относительные пути (с ..) таким образом будут зарезаны. Если слеши правда тоже нельзя, это незачёт сразу :) Поправьте, пожалуйста.

А я там не самом пути запрещаю, а в названии папки. В цикле прохожусь по ее символам.

2020-10-26 13:57 UTC, yurii-litvinov commented
> > Запретить все точки в пути для скачивания --- очень плохая идея, хотя бы потому, что путь до проекта содержит точку (homework.sem3). Ну и все относительные пути (с ..) таким образом будут зарезаны. Если слеши правда тоже нельзя, это незачёт сразу :) Поправьте, пожалуйста.
> 
> А я там не самом пути запрещаю, а в названии папки. В цикле прохожусь по ее символам.

А что это меняет? :)

2020-10-26 14:05 UTC, AlinaRodina99 commented
> > > Запретить все точки в пути для скачивания --- очень плохая идея, хотя бы потому, что путь до проекта содержит точку (homework.sem3). Ну и все относительные пути (с ..) таким образом будут зарезаны. Если слеши правда тоже нельзя, это незачёт сразу :) Поправьте, пожалуйста.
> > 
> > 
> > А я там не самом пути запрещаю, а в названии папки. В цикле прохожусь по ее символам.
> 
> А что это меняет? :)

Да ,что-то с точками неправильно, но вот слэшей же не должно быть в названии папки, как и остальных знаков, кроме точки, если она не в начале названия

2020-10-26 14:07 UTC, yurii-litvinov commented
> > > > Запретить все точки в пути для скачивания --- очень плохая идея, хотя бы потому, что путь до проекта содержит точку (homework.sem3). Ну и все относительные пути (с ..) таким образом будут зарезаны. Если слеши правда тоже нельзя, это незачёт сразу :) Поправьте, пожалуйста.
> > > 
> > > 
> > > А я там не самом пути запрещаю, а в названии папки. В цикле прохожусь по ее символам.
> > 
> > 
> > А что это меняет? :)
> 
> Да ,что-то с точками неправильно, но вот слэшей же не должно быть в названии папки, как и остальных знаков, кроме точки, если она не в начале названия

А там точно именно название папки, а не путь должен быть? Если я хочу скачать на десктоп или в Downloads, что мне делать?

2020-10-26 14:10 UTC, AlinaRodina99 commented
> > > > > Запретить все точки в пути для скачивания --- очень плохая идея, хотя бы потому, что путь до проекта содержит точку (homework.sem3). Ну и все относительные пути (с ..) таким образом будут зарезаны. Если слеши правда тоже нельзя, это незачёт сразу :) Поправьте, пожалуйста.
> > > > 
> > > > 
> > > > А я там не самом пути запрещаю, а в названии папки. В цикле прохожусь по ее символам.
> > > 
> > > 
> > > А что это меняет? :)
> > 
> > 
> > Да ,что-то с точками неправильно, но вот слэшей же не должно быть в названии папки, как и остальных знаков, кроме точки, если она не в начале названия
> 
> А там точно именно название папки, а не путь должен быть? Если я хочу скачать на десктоп или в Downloads, что мне делать?

Это я похоже не предусмотрела( У меня надо вводить либо папку в текущей открытой папке, либо создать новую в текущей  , и туда все качать

2020-10-26 14:16 UTC, AlinaRodina99 commented
> > > > > Запретить все точки в пути для скачивания --- очень плохая идея, хотя бы потому, что путь до проекта содержит точку (homework.sem3). Ну и все относительные пути (с ..) таким образом будут зарезаны. Если слеши правда тоже нельзя, это незачёт сразу :) Поправьте, пожалуйста.
> > > > 
> > > > 
> > > > А я там не самом пути запрещаю, а в названии папки. В цикле прохожусь по ее символам.
> > > 
> > > 
> > > А что это меняет? :)
> > 
> > 
> > Да ,что-то с точками неправильно, но вот слэшей же не должно быть в названии папки, как и остальных знаков, кроме точки, если она не в начале названия
> 
> А там точно именно название папки, а не путь должен быть? Если я хочу скачать на десктоп или в Downloads, что мне делать?

То есть по заданию нужно иметь возможность скачать в любую папку на компе?

2020-10-27 06:28 UTC, yurii-litvinov commented
> > > > > > Запретить все точки в пути для скачивания --- очень плохая идея, хотя бы потому, что путь до проекта содержит точку (homework.sem3). Ну и все относительные пути (с ..) таким образом будут зарезаны. Если слеши правда тоже нельзя, это незачёт сразу :) Поправьте, пожалуйста.
> > > > > 
> > > > > 
> > > > > А я там не самом пути запрещаю, а в названии папки. В цикле прохожусь по ее символам.
> > > > 
> > > > 
> > > > А что это меняет? :)
> > > 
> > > 
> > > Да ,что-то с точками неправильно, но вот слэшей же не должно быть в названии папки, как и остальных знаков, кроме точки, если она не в начале названия
> > 
> > 
> > А там точно именно название папки, а не путь должен быть? Если я хочу скачать на десктоп или в Downloads, что мне делать?
> 
> То есть по заданию нужно иметь возможность скачать в любую папку на компе?

Ну это типа ожидается, особенно если у нас есть контрол, куда можно ввести имя папки. В реальной жизни все такие контролы принимают путь.

2020-10-27 16:57 UTC, merged